version: "3"
services: 
  mongo:
    container_name: mongodb 
    image: mongo
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/mongodb
  mongo-express:
      container_name: express
      image: mongo-express
      depends_on: 
        - mongo
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: secret
  restapi:
    build: mic_asistencia
    container_name: asistencia-restapi
    ports:
      - "4000:4000"
